export const TRACKABLE_LINK_DATA_SEEDS = [
  {
    linkName: 'Summer Campaign 2023',
    websiteUrl: 'https://example.com/summer-sale',
    generatedUrl: 'https://track.example.com/summer-campaign-2023',
    campaignName: 'Summer Sale 2023',
    campaignSource: 'Email Marketing',
    meansOfCommunication: 'Email',
    keyword: 'summer',
  },
  {
    linkName: 'Winter Promotion 2023',
    websiteUrl: 'https://example.com/winter-deals',
    generatedUrl: 'https://track.example.com/winter-promotion-2023',
    campaignName: 'Winter Deals 2023',
    campaignSource: 'Social Media',
    meansOfCommunication: 'Instagram',
    keyword: 'winter',
  },
  {
    linkName: 'Black Friday 2023',
    websiteUrl: 'https://example.com/black-friday',
    generatedUrl: 'https://track.example.com/black-friday-2023',
    campaignName: 'Black Friday 2023',
    campaignSource: 'Google Ads',
    meansOfCommunication: 'Search Engine',
    keyword: 'blackfriday',
  },
  {
    linkName: 'New Year Kickoff 2024',
    websiteUrl: 'https://example.com/new-year-sale',
    generatedUrl: 'https://track.example.com/new-year-kickoff-2024',
    campaignName: 'New Year Sale 2024',
    campaignSource: 'Affiliate Marketing',
    meansOfCommunication: 'Blogs',
    keyword: 'newyear',
  },
  {
    linkName: 'Spring Clearance 2024',
    websiteUrl: 'https://example.com/spring-clearance',
    generatedUrl: 'https://track.example.com/spring-clearance-2024',
    campaignName: 'Spring Clearance 2024',
    campaignSource: 'Influencer Marketing',
    meansOfCommunication: 'YouTube',
    keyword: 'spring',
  },
];
