name: kvoipv2

services:
  change-vol-ownership:
    container_name: kvoipv2-change-vol-ownership
    image: ubuntu
    user: root
    volumes:
      - server-local-data:/tmp/server-local-data
      - docker-data:/tmp/docker-data
    command: >
      bash -c "
      chown -R 1000:1000 /tmp/server-local-data
      && chown -R 1000:1000 /tmp/docker-data"

  server:
    container_name: kvoipv2-server
    build:
      context: ../..
      dockerfile: ./packages/twenty-docker/twenty/Dockerfile
    image: kvoipcrm/v2:${TAG:-latest}
    volumes:
      - server-local-data:/app/packages/twenty-server/${STORAGE_LOCAL_PATH:-.local-storage}
      - docker-data:/app/docker-data
      - ${SSL_KEY_PATH}:${SSL_KEY_PATH}
      - ${SSL_CERT_PATH}:${SSL_CERT_PATH}
    ports:
      - "${SERVER_PORT:-3000}:3000"
    environment:
      PORT: 3000
      PG_DATABASE_URL: postgres://${PG_DATABASE_USER:-postgres}:${PG_DATABASE_PASSWORD:-postgres}@${PG_DATABASE_HOST:-db}:${PG_DATABASE_PORT:-5432}/${PG_DATABASE:-postgres}
      SERVER_URL: ${SERVER_URL}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}

      STORAGE_TYPE: ${STORAGE_TYPE}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_S3_NAME: ${STORAGE_S3_NAME}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}

      APP_SECRET: ${APP_SECRET}

      REACT_APP_CHATBOT_BASE_URL: ${REACT_APP_CHATBOT_BASE_URL:-http://localhost:8080}

      IS_MULTIWORKSPACE_ENABLED: ${IS_MULTIWORKSPACE_ENABLED:-true}

      DISABLE_DB_MIGRATIONS: ${DISABLE_DB_MIGRATIONS:-true}
      SSL_KEY_PATH: ${SSL_KEY_PATH}
      SSL_CERT_PATH: ${SSL_CERT_PATH}    
      
    depends_on:
      change-vol-ownership:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3000/healthz
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 120s
    restart: on-failure

  worker:
    container_name: kvoipv2-worker
    image: kvoipcrm/v2:${TAG:-latest}
    command: ["yarn", "worker:prod"]
    environment:
      PG_DATABASE_URL: postgres://${PG_DATABASE_USER:-postgres}:${PG_DATABASE_PASSWORD:-postgres}@${PG_DATABASE_HOST:-db}:${PG_DATABASE_PORT:-5432}/${PG_DATABASE}
      SERVER_URL: ${SERVER_URL}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      DISABLE_DB_MIGRATIONS: "true" # it already runs on the server

      STORAGE_TYPE: ${STORAGE_TYPE}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_S3_NAME: ${STORAGE_S3_NAME}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}

      APP_SECRET: ${APP_SECRET}
    depends_on:
      db:
        condition: service_healthy
      server:
        condition: service_healthy
    restart: always

  db:
    container_name: kvoipv2-pg
    image: kvoipcrm-v2/kvoip-pg-spilo:latest
    build:
      context: ../..
      dockerfile: ./packages/twenty-docker/twenty-postgres-spilo/Dockerfile
    volumes:
      - db-data:/home/postgres/pgdata
    environment:
      PGUSER_SUPERUSER: ${PG_DATABASE_USER:-postgres}
      PGPASSWORD_SUPERUSER: ${PG_DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${PG_DATABASE:-postgres}
      ALLOW_NOSSL: "true"
      SPILO_PROVIDER: "local"
    ports: 
      - "5433:5432"
    healthcheck:
      test: pg_isready -U ${PG_DATABASE_USER:-postgres} -h db -d postgres
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  redis:
    container_name: kvoipv2-redis
    image: redis
    restart: always

volumes:
  docker-data:
  db-data:
  server-local-data:
