export enum SettingsPath {
  ProfilePage = 'profile',
  TwoFactorAuthenticationStrategyConfig = 'profile/two-factor-authentication/:twoFactorAuthenticationStrategy',
  Experience = 'experience',
  Accounts = 'accounts',
  NewAccount = 'accounts/new',
  AccountsCalendars = 'accounts/calendars',
  AccountsEmails = 'accounts/emails',
  NewImapSmtpCaldavConnection = 'accounts/new-imap-smtp-caldav-connection',
  EditImapSmtpCaldavConnection = 'accounts/edit-imap-smtp-caldav-connection/:connectedAccountId',
  Billing = 'billing',
  Objects = 'objects',
  ObjectOverview = 'objects/overview',
  ObjectDetail = 'objects/:objectNamePlural',
  ObjectNewFieldSelect = 'objects/:objectNamePlural/new-field/select',
  ObjectNewFieldConfigure = 'objects/:objectNamePlural/new-field/configure',
  ObjectFieldEdit = 'objects/:objectNamePlural/:fieldName',
  NewObject = 'objects/new',
  ServerlessFunctions = 'functions',
  NewServerlessFunction = 'functions/new',
  ServerlessFunctionDetail = 'functions/:serverlessFunctionId',

  ServiceCenter = 'service-center',
  ServiceCenterSectors = 'service-center/sectors',
  ServiceCenterNewSector = 'service-center/sectors/new',
  ServiceCenterEditSector = 'service-center/sectors/:sectorSlug/edit',
  ServiceCenterAgents = 'service-center/agents',
  ServiceCenterNewAgent = 'service-center/agents/new',
  ServiceCenterEditAgent = 'service-center/agents/:agentSlug/edit',
  ServiceCenterTelephony = 'service-center/telephony',
  ServiceCenterNewTelephonyExtension = 'service-center/telephony/new',
  ServiceCenterLinkTelephonyExtension = 'service-center/telephony/link/:extensionNumber',
  EditTelephony = 'service-center/telephony/:telephonySlug/edit',
  ServiceCenterServiceLevel = 'service-center/sla',
  ServiceCenterEditServiceLevel = 'service-center/service-level/:slaSlug/edit',
  Chatbots = 'chatbots/',
  ChatbotsCreate = 'chatbots/create',
  ChatbotsEdit = 'chatbots/:chatbotSlug/edit',
  ChatbotFlow = 'chatbots/flow/:id',

  FinancialClosing = 'financial-closing',
  FinancialClosingNew = 'financial-closing/new',
  FinancialClosingEdit = 'financial-closing/:financialClosingId/edit',
  FinancialClosingExecutions = 'financial-closing/:financialClosingId/executions',
  FinancialClosingExecution = 'financial-closing/executions/:financialClosingExecutionId',
  CompanyFinancialClosingExecutions = 'financial-closing/company-executions/:financialClosingExecutionId',
  CompanyFinancialClosingExecution = 'financial-closing/company-execution/:companyFinancialClosingExecutionId',

  WorkspaceMembersPage = 'members',
  Workspace = 'general',
  Domains = 'domains',
  Domain = 'domains/domain',
  NewApprovedAccessDomain = 'domains/approved-access-domain/new',
  Releases = 'releases',
  AI = 'ai',
  AINewAgent = 'ai/new-agent',
  AIAgentDetail = 'ai/agents/:agentId',
  ApiWebhooks = 'api-webhooks',
  RestPlayground = 'playground/rest/:schema',
  GraphQLPlayground = 'playground/graphql/:schema',
  NewApiKey = 'api-webhooks/apis/new',
  ApiKeyDetail = 'api-webhooks/apis/:apiKeyId',
  NewWebhook = 'api-webhooks/webhooks/new',
  WebhookDetail = 'api-webhooks/webhooks/:webhookId',
  Integrations = 'integrations',
  IntegrationMCP = 'integrations/mcp',
  IntegrationDatabase = 'integrations/:databaseKey',
  IntegrationDatabaseConnection = 'integrations/:databaseKey/:connectionId',
  IntegrationEditDatabaseConnection = 'integrations/:databaseKey/:connectionId/edit',
  IntegrationNewDatabaseConnection = 'integrations/:databaseKey/new',
  IntegrationWhatsappDatabase = 'integrations/whatsapp',
  IntegrationWhatsappNewDatabaseConnection = 'integrations/whatsapp/new',
  IntegrationWhatsappEditDatabaseConnection = 'integrations/whatsapp/:connectionId/edit',

  IntegrationInterDatabase = 'integrations/inter',
  IntegrationInterNewDatabaseConnection = 'integrations/inter/new',
  IntegrationInterEditDatabaseConnection = 'integrations/inter/:connectionId/edit',

  IntegrationFocusNfe = 'integrations/focus-nfe',
  IntegrationFocusNfeNewDatabaseConnection = 'integrations/focus-nfe/new',
  IntegrationFocusNfeEditDatabaseConnection = 'integrations/focus-nfe/:connectionId/edit',

  IntegrationFocusNfeNewIssuer = 'integrations/focus-nfe/new-issuer',
  IntegrationFocusNfeEditIssuer = 'integrations/focus-nfe/:issuerId/edit-issuer',

  Security = 'security',
  NewSSOIdentityProvider = 'security/sso/new',

  AdminPanel = 'admin-panel',
  AdminPanelHealthStatus = 'admin-panel#health-status',
  AdminPanelIndicatorHealthStatus = 'admin-panel/health-status/:indicatorId',
  AdminPanelConfigVariableDetails = 'admin-panel/config-variables/:variableName',

  Roles = 'roles',
  RoleCreate = 'roles/create',
  RoleDetail = 'roles/:roleId',
  RoleObjectLevel = 'roles/:roleId/object/:objectMetadataId',
  RoleAddObjectLevel = 'roles/:roleId/add-object-permission',
  PageLayout = 'page-layout',
  PageLayoutNew = 'page-layout/new',
  PageLayoutEdit = 'page-layout/:id',
}
